- name: Deploy | as user
  block:
  - name: Get source
    git:
      repo: 'https://github.com/homebot/homebot.git'
      dest: "{{ www_dir }}/homebot"
    tags:
      - git
  - name: Install packages based on package.json.
    npm:
      path: "{{ www_dir }}/homebot"
    tags:
      - npm
  tags: deploy
